-- v2 creacion schema y llenado de las tablas
-- MySQL Script generated by MySQL Workbench
-- Sat Jul  1 22:50:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyectoSchemaDefinitivo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyectoSchemaDefinitivo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyectoSchemaDefinitivo` DEFAULT CHARACTER SET utf8 ;
USE `proyectoSchemaDefinitivo` ;

-- -----------------------------------------------------
-- Table `proyectoSchemaDefinitivo`.`IndicadorPobreza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoSchemaDefinitivo`.`IndicadorPobreza` ;

CREATE TABLE IF NOT EXISTS `proyectoSchemaDefinitivo`.`IndicadorPobreza` (
  `dic21` DOUBLE NULL,
  `dic22` DOUBLE NULL,
  `variacionSignificativa` VARCHAR(2) NULL,
  `area` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectoSchemaDefinitivo`.`Provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoSchemaDefinitivo`.`Provincia` ;

CREATE TABLE IF NOT EXISTS `proyectoSchemaDefinitivo`.`Provincia` (
  `idProvincia` INT NOT NULL,
  `nombreProvincia` VARCHAR(45) NULL,
  PRIMARY KEY (`idProvincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectoSchemaDefinitivo`.`Ubicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoSchemaDefinitivo`.`Ubicacion` ;

CREATE TABLE IF NOT EXISTS `proyectoSchemaDefinitivo`.`Ubicacion` (
  `idUbicacion` BIGINT(200) NOT NULL,
  `ciudad` VARCHAR(15) NULL,
  `conglomerado` VARCHAR(8) NULL,
  `IndicadorPobreza_area` VARCHAR(6) NOT NULL,
  `Provincia_idProvincia` INT NOT NULL,
  PRIMARY KEY (`idUbicacion`, `IndicadorPobreza_area`, `Provincia_idProvincia`),
  INDEX `fk_Ubicacion_IndicadorPobreza1_idx` (`IndicadorPobreza_area` ASC) VISIBLE,
  INDEX `fk_Ubicacion_Provincia1_idx` (`Provincia_idProvincia` ASC) VISIBLE,
  CONSTRAINT `fk_Ubicacion_IndicadorPobreza1`
    FOREIGN KEY (`IndicadorPobreza_area`)
    REFERENCES `proyectoSchemaDefinitivo`.`IndicadorPobreza` (`area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ubicacion_Provincia1`
    FOREIGN KEY (`Provincia_idProvincia`)
    REFERENCES `proyectoSchemaDefinitivo`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectoSchemaDefinitivo`.`ServicioHigienico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoSchemaDefinitivo`.`ServicioHigienico` ;

CREATE TABLE IF NOT EXISTS `proyectoSchemaDefinitivo`.`ServicioHigienico` (
  `idServicioHigienico` INT NOT NULL,
  `tipoServicioHigienico` VARCHAR(25) NULL,
  `instalacionSanitariaCercanaOPrestrada` VARCHAR(25) NULL,
  `noServicioHigienicoEntonces` VARCHAR(90) NULL,
  PRIMARY KEY (`idServicioHigienico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectoSchemaDefinitivo`.`Vivienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoSchemaDefinitivo`.`Vivienda` ;

CREATE TABLE IF NOT EXISTS `proyectoSchemaDefinitivo`.`Vivienda` (
  `idVivienda` DOUBLE NOT NULL,
  `accesoVivienda` VARCHAR(50) NULL,
  `tipoVivienda` VARCHAR(35) NOT NULL,
  `pisoMaterial` VARCHAR(75) NOT NULL,
  `pisoEstado` VARCHAR(7) NOT NULL,
  `paredMaterial` VARCHAR(50) NULL,
  `paredEstado` VARCHAR(7) NULL,
  `cubiertaTecho` VARCHAR(72) NULL,
  `cubiertaEstado` VARCHAR(7) NULL,
  `eliminaBasura` VARCHAR(45) NULL,
  `Ubicacion_idUbicacion` BIGINT(200) NOT NULL,
  `ServicioHigienico_idServicioHigienico` INT NOT NULL,
  PRIMARY KEY (`idVivienda`, `ServicioHigienico_idServicioHigienico`),
  INDEX `fk_Vivienda_Ubicacion_idx` (`Ubicacion_idUbicacion` ASC) VISIBLE,
  INDEX `fk_Vivienda_ServicioHigienico1_idx` (`ServicioHigienico_idServicioHigienico` ASC) VISIBLE,
  CONSTRAINT `fk_Vivienda_Ubicacion`
    FOREIGN KEY (`Ubicacion_idUbicacion`)
    REFERENCES `proyectoSchemaDefinitivo`.`Ubicacion` (`idUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vivienda_ServicioHigienico1`
    FOREIGN KEY (`ServicioHigienico_idServicioHigienico`)
    REFERENCES `proyectoSchemaDefinitivo`.`ServicioHigienico` (`idServicioHigienico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectoSchemaDefinitivo`.`Hogar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoSchemaDefinitivo`.`Hogar` ;

CREATE TABLE IF NOT EXISTS `proyectoSchemaDefinitivo`.`Hogar` (
  `idHogar` DOUBLE NOT NULL,
  `numCuartos` INT NULL,
  `numDormitorios` INT NULL,
  `cuartoNegocio` VARCHAR(2) NULL,
  `tipoAlumbrado` VARCHAR(100) NULL,
  `tieneHogarMotos` VARCHAR(2) NULL,
  `numMotos` VARCHAR(15) NULL,
  `tieneHogarVehiculos` VARCHAR(2) NULL,
  `numVehiculos` VARCHAR(20) NULL,
  `materialesCocinan` VARCHAR(12) NULL,
  `cuartoCocina` VARCHAR(2) NULL,
  `Vivienda_idVivienda` DOUBLE NOT NULL,
  PRIMARY KEY (`idHogar`, `Vivienda_idVivienda`),
  INDEX `fk_Hogar_Vivienda1_idx` (`Vivienda_idVivienda` ASC) VISIBLE,
  CONSTRAINT `fk_Hogar_Vivienda1`
    FOREIGN KEY (`Vivienda_idVivienda`)
    REFERENCES `proyectoSchemaDefinitivo`.`Vivienda` (`idVivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectoSchemaDefinitivo`.`arriendo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoSchemaDefinitivo`.`arriendo` ;

CREATE TABLE IF NOT EXISTS `proyectoSchemaDefinitivo`.`arriendo` (
  `idarriendo` INT NOT NULL,
  `valorArriendo` DOUBLE NULL,
  `incluyePagoAgua` VARCHAR(2) NULL,
  `incluyePagoLuz` VARCHAR(2) NULL,
  `parentezcoPropietarioVivienda` VARCHAR(2) NULL,
  `Hogar_idHogar` DOUBLE NOT NULL,
  PRIMARY KEY (`idarriendo`, `Hogar_idHogar`),
  INDEX `fk_arriendo_Hogar1_idx` (`Hogar_idHogar` ASC) VISIBLE,
  CONSTRAINT `fk_arriendo_Hogar1`
    FOREIGN KEY (`Hogar_idHogar`)
    REFERENCES `proyectoSchemaDefinitivo`.`Hogar` (`idHogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectoSchemaDefinitivo`.`ServicioPotable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoSchemaDefinitivo`.`ServicioPotable` ;

CREATE TABLE IF NOT EXISTS `proyectoSchemaDefinitivo`.`ServicioPotable` (
  `idServicioPotable` INT NOT NULL auto_increment,
  `dondeObtieneAgua` VARCHAR(40) NULL,
  `tieneMedidorAgua` VARCHAR(2) NULL,
  `esJuntaAgua` VARCHAR(2) NULL,
  `aguaRecibelaVivienda` VARCHAR(90) NULL,
  `servicioDucha` VARCHAR(50) NULL,
  `Vivienda_idVivienda` DOUBLE NOT NULL,
  PRIMARY KEY (`idServicioPotable`, `Vivienda_idVivienda`),
  INDEX `fk_ServicioPotable_Vivienda1_idx` (`Vivienda_idVivienda` ASC) VISIBLE,
  CONSTRAINT `fk_ServicioPotable_Vivienda1`
    FOREIGN KEY (`Vivienda_idVivienda`)
    REFERENCES `proyectoSchemaDefinitivo`.`Vivienda` (`idVivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectoSchemaDefinitivo`.`Combustible`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoSchemaDefinitivo`.`Combustible` ;

CREATE TABLE IF NOT EXISTS `proyectoSchemaDefinitivo`.`Combustible` (
  `idCombustibles` INT NOT NULL,
  `abastecimientoSuper` VARCHAR(7) NULL,
  `gastoSuper` VARCHAR(10) NULL,
  `abastecimientoExtra` VARCHAR(7) NULL,
  `gastoExtra` VARCHAR(10) NULL,
  `abastecimientoDiesel` VARCHAR(7) NULL,
  `gastoDisel` VARCHAR(10) NULL,
  `abastecimientoEco_Pais` VARCHAR(7) NULL,
  `gastoEco_Pais` VARCHAR(10) NULL,
  `abastecimientoEletricidad` VARCHAR(7) NULL,
  `gastoElectricidad` VARCHAR(10) NULL,
  `abastecimientoGas` VARCHAR(7) NULL,
  `gastoGas` VARCHAR(10) NULL,
  `Hogar_idHogar` DOUBLE NOT NULL,
  PRIMARY KEY (`idCombustibles`, `Hogar_idHogar`),
  INDEX `fk_Combustible_Hogar1_idx` (`Hogar_idHogar` ASC) VISIBLE,
  CONSTRAINT `fk_Combustible_Hogar1`
    FOREIGN KEY (`Hogar_idHogar`)
    REFERENCES `proyectoSchemaDefinitivo`.`Hogar` (`idHogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectoSchemaDefinitivo`.`TasaDesempleo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoSchemaDefinitivo`.`TasaDesempleo` ;

CREATE TABLE IF NOT EXISTS `proyectoSchemaDefinitivo`.`TasaDesempleo` (
  `year19` DOUBLE NULL,
  `year21` DOUBLE NULL,
  `Provincia_idProvincia` INT NOT NULL,
  `diferencia` DOUBLE NULL,
  PRIMARY KEY (`Provincia_idProvincia`),
  CONSTRAINT `fk_TasaDesempleo_Provincia1`
    FOREIGN KEY (`Provincia_idProvincia`)
    REFERENCES `proyectoSchemaDefinitivo`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectoSchemaDefinitivo`.`TasaEmpleoAdecuado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoSchemaDefinitivo`.`TasaEmpleoAdecuado` ;

CREATE TABLE IF NOT EXISTS `proyectoSchemaDefinitivo`.`TasaEmpleoAdecuado` (
  `year19` DOUBLE NULL,
  `year21` DOUBLE NULL,
  `Provincia_idProvincia` INT NOT NULL,
  `diferencia` DOUBLE NULL,
  PRIMARY KEY (`Provincia_idProvincia`),
  CONSTRAINT `fk_TasaDesempleo_Provincia10`
    FOREIGN KEY (`Provincia_idProvincia`)
    REFERENCES `proyectoSchemaDefinitivo`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectoSchemaDefinitivo`.`CoeficienteGini`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoSchemaDefinitivo`.`CoeficienteGini` ;

CREATE TABLE IF NOT EXISTS `proyectoSchemaDefinitivo`.`CoeficienteGini` (
  `year19` DOUBLE NULL,
  `year21` DOUBLE NULL,
  `Provincia_idProvincia` INT NOT NULL,
  `diferencia` DOUBLE NULL,
  PRIMARY KEY (`Provincia_idProvincia`),
  CONSTRAINT `fk_TasaDesempleo_Provincia11`
    FOREIGN KEY (`Provincia_idProvincia`)
    REFERENCES `proyectoSchemaDefinitivo`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectoSchemaDefinitivo`.`TasaResolucionAmbitoPenal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectoSchemaDefinitivo`.`TasaResolucionAmbitoPenal` ;

CREATE TABLE IF NOT EXISTS `proyectoSchemaDefinitivo`.`TasaResolucionAmbitoPenal` (
  `year2022` DOUBLE NULL,
  `Provincia_idProvincia` INT NOT NULL,
  PRIMARY KEY (`Provincia_idProvincia`),
  CONSTRAINT `fk_TasaDesempleo_Provincia110`
    FOREIGN KEY (`Provincia_idProvincia`)
    REFERENCES `proyectoSchemaDefinitivo`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;






-- -----------------------------------------------------------------------------------------------------------------------
-- indicadorpobreza

-- este sirve
INSERT INTO proyectoSchemaDefinitivo.indicadorpobreza (dic22, dic21, variacionSignificativa, area) VALUES (17.8, 20.8, 'no', 'urbano');
INSERT INTO proyectoSchemaDefinitivo.indicadorpobreza (dic22, dic21, variacionSignificativa, area) VALUES (41.0, 42.4, 'no', 'rural');
-- -----------------------------------------------------------------------------------------------------------------------
-- provincia
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (01, 'Azuay');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (02, 'Bolivar');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (03, 'Cañar');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (04, 'Carchi');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (05, 'Cotopaxi');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (06, 'Chimborazo');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (07, 'Oro');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (08, 'Esmeraldas');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (09, 'Guayas');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (10, 'Imbabura');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (11, 'Loja');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (12, 'Los Rios');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (13, 'Manabi');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (14, 'Morona Santiago');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (15, 'Napo');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (16, 'Pastaza');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (17, 'Pichincha');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (18, 'Tungurahua');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (19, 'Zamora Chinchipe');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (20, 'Galapagos');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (21, 'Sucumbíos');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (22, 'Orellana');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (23, 'Santo Domingo de los Tsáchilas');
INSERT INTO proyectoSchemaDefinitivo.provincia (idProvincia, nombreProvincia) VALUES (24, 'Santa Elena');


-- -----------------------------------------------------------------------------------------------------------------------
-- tasa de empleo adecuado

-- este sirve
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (42.2, 38.8, 1, -5.4);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (20.9, 17.0, 2, -4.0);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (30.9, 26.8, 3, -4.1);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (28.7, 24.7, 4, -3.9);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (26.2, 25.6, 5, -0.7);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (19.3, 16.1, 6, -3.2);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (47.2, 37.2, 7, -10.0);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (24.0, 21.7, 8, -2.2);-- ESMERALDAS
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (45.0, 37.4, 9, -7.6);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (31.6, 30.1, 10, -1.5);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (26.9, 26.0, 11, -1.0);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (31.9, 28.6, 12, -3.3); -- los rios
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (30.1, 26.9, 13, -3.2);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (15.7, 13.9, 14, -1.8);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (18.9, 14.2, 15, -4.7);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (22.4, 18.9, 16, -3.5);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (53.0, 43.6, 17, -9.5); -- pichincha
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (32.9, 24.5, 18, -8.4);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (27.4, 30.8, 19, 3.4);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (65.2, 36.0, 20, -29.2);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (27.1, 24.8, 21, -2.4);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (20.3, 17.6, 22, -2.7);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (37.2, 32.2, 23, -5.1);
INSERT INTO proyectoSchemaDefinitivo.tasaempleoadecuado (year19, year21, Provincia_idProvincia, diferencia) VALUES (33.9, 30.3, 24, -3.7);



-- -----------------------------------------------------------------------------------------------------------------------
-- tasa desmpleo

-- este sirve
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (3.4, 5.1, 1, 1.7);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (1.4, 1.1, 2, -0.3);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (3.9, 4.0, 3, 0.1);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (4.9, 6.3, 4, 1.4);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (1.7, 2.8, 5, 1.1);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (1.3, 2.3, 6, 1.0);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (4.9, 6.9, 7, 2.0);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (10.4, 10.0, 8, -0.4);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (3.1, 3.9, 9, 0.8);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (6.8, 6.0, 10, -0.8);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (3.6, 4.1, 11, 0.5);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (2.8, 2.8, 12, 0.0);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (2.3, 2.6, 13, 0.3);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (1.3, 1.4, 14, 0.1);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (2.2, 2.3, 15, 0.1);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (1.9, 2.0, 16, 0.1);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (8.0, 10.8, 17, 2.8);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (2.2, 3.1, 18, 0.9);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (3.1, 3.0, 19, -0.1);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (2.1, 9.3, 20, 7.2);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (4.7, 5.4, 21, 0.7);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (1.8, 2.6, 22, 0.8);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (2.8, 3.7, 23, 0.9);
INSERT INTO proyectoSchemaDefinitivo.tasadesempleo (year19, year21, Provincia_idProvincia, diferencia) VALUES (2.8, 3.6, 24, 0.8);


-- -----------------------------------------------------------------------------------------------------------------------
-- Resolución por Provincia ÁmbitoPenal

INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (1.03, 14);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.93, 3);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.94, 2);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.94, 17);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.94, 16);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.92, 11);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.88, 8);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.87, 10); -- imbabura
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.86, 18);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.85, 1);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.85, 24);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.84, 21);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.84, 23);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.84, 13);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.84, 9);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.83, 4);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.83, 5);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.82, 6);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.81, 12);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.81, 19);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.79, 7);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.72, 20);
INSERT INTO proyectoSchemaDefinitivo.tasaresolucionambitopenal (year2022, Provincia_idProvincia) VALUES (0.71, 15);


-- -----------------------------------------------------------------------------------------------------------------------
-- coeficiente gini

-- este sirve

INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.43, 0.44, 1, 0.01);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.44, 0.47, 2, 0.03);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.41 ,0.44, 3, 0.03);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.53 ,0.48, 4, -0.05);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.47 ,0.45, 5, -0.02);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.52 ,0.48, 6, -0.02);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.40 ,0.42, 7, 0.03);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.54 ,0.50, 8, -0.03);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.42 ,0.45, 9, 0.04);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.50 ,0.47, 10, -0.04);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.48 ,0.48, 11, 0.00);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.40 ,0.43, 12, 0.03);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.42 ,0.46, 13, 0.05);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.53 ,0.55, 14, 0.02);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.60 ,0.57, 15, -0.03);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.58 ,0.55, 16, -0.03);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.47 ,0.51, 17, 0.04);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.47 ,0.47, 18, 0.01);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.47 ,0.50, 19, 0.02);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.00 ,0.00, 20, 0.00);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.55 ,0.50, 21, -0.05);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.60 ,0.53, 22, -0.07);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.42 ,0.44, 23, 0.02);
INSERT INTO proyectoSchemaDefinitivo.CoeficienteGini (year19, year21, Provincia_idProvincia, diferencia) VALUES (0.40 ,0.41, 24, 0.01);


-- -----------------------------------------------------------------------------------------------------------------------
-- ubicacion


-- este sirve
INSERT INTO  proyectoSchemaDefinitivo.ubicacion(
                    idUbicacion,
                    ciudad,
                    conglomerado,
                    IndicadorPobreza_area,
                    Provincia_idProvincia
                    )

SELECT ROW_NUMBER() OVER (ORDER BY v.ciudad) AS id,
       v.ciudad, v.conglomerado, v.area, n.provincia
FROM vivienda.enemdu_vivienda_final v
JOIN vivienda.nueva_tabla n ON v.id = n.id
JOIN proyectoSchemaDefinitivo.provincia p ON p.idProvincia = n.provincia;

-- -----------------------------------------------------------------------------------------------------------------------
-- servicio higienico
-- este sirve
INSERT INTO  proyectoSchemaDefinitivo.serviciohigienico(
                    idServicioHigienico,
                    tipoServicioHigienico,
                    instalacionSanitariaCercanaOPrestrada,
                    noServicioHigienicoEntonces
                    )

SELECT ROW_NUMBER() OVER (ORDER BY v.tipoServicioHigienico) AS id,
       v.tipoServicioHigienico, v.instalacionSanitariaCercanaOPrestada, v.noServicioHigienicoEntonces
FROM vivienda.enemdu_vivienda_final v;
-- -----------------------------------------------------------------------------------------------------



INSERT INTO proyectoSchemaDefinitivo.Vivienda (
  idVivienda,
  accesoVivienda,
  tipoVivienda,
  pisoMaterial,
  pisoEstado,
  paredMaterial,
  paredEstado,
  cubiertaTecho,
  cubiertaEstado,
  eliminaBasura,
  Ubicacion_idUbicacion,
  ServicioHigienico_idServicioHigienico
)
select v.id_vivienda, v.accesoVivienda, v.tipoVivienda, v.pisoMaterial,
       v.pisoEstado, v.paredMaterial, v.paredEstado, v.cuviertaTecho,
       v.cuviertaEstado, v.eliminaBasura, u.idUbicacion, s.idServicioHigienico
from vivienda.enemdu_vivienda_final v
JOIN proyectoschemadefinitivo.ubicacion u ON v.id = u.idUbicacion
JOIN proyectoSchemaDefinitivo.ServicioHigienico s ON u.idUbicacion = s.idServicioHigienico;





-- --------------------
INSERT INTO `proyectoSchemaDefinitivo`.`ServicioPotable`(
  dondeObtieneAgua,
  tieneMedidorAgua,
  esJuntaAgua,
  aguaRecibelaVivienda,
  servicioDucha,
  Vivienda_idVivienda
)
SELECT distinct v.dondeObtieneAgua, v.tieneMedidorAgua, v.esJuntaAgua, v.aguaRecibelaVivienda, v.servicioDucha, v2.idVivienda
FROM vivienda.enemdu_vivienda_final v
INNER JOIN proyectoSchemaDefinitivo.vivienda v2
ON v.id_vivienda = v2.idVivienda;

-- --------------------------------------------------------

-- -----------------------------------------------------
-- hogar

INSERT INTO `proyectoSchemaDefinitivo`.`Hogar` (
                                            idHogar,
                                            numCuartos,
                                            numDormitorios,
                                            cuartoNegocio,
                                            tipoAlumbrado,
                                            tieneHogarMotos,
                                            numMotos,
                                            tieneHogarVehiculos,
                                            numVehiculos,
                                            materialesCocinan,
                                            cuartoCocina,
                                            Vivienda_idVivienda
)
SELECT
    e.id_hogar,
    e.numCuartos,
    e.numDormitorios,
    e.cuartoNegocio,
    e.tipoAlumbrado,
    e.tieneHogarMotos,
    e.numMotos,
    e.tieneHogarVehiculos,
    e.numVehiculos,
    e.materialesCocinan,
    e.cuartoCocina,
    e.id_vivienda
FROM vivienda.enemdu_vivienda_final e;

-- ------------------------------------------



INSERT INTO `proyectoSchemaDefinitivo`.`Combustible`(
	idCombustibles,
	abastecimientoSuper,
    gastoSuper,
    abastecimientoExtra,
    gastoExtra,
    abastecimientoDiesel,
    gastoDisel,
    abastecimientoEco_Pais,
    gastoEco_Pais,
    abastecimientoEletricidad,
    gastoElectricidad,
    abastecimientoGas,
    gastoGas,
    Hogar_idHogar
)
SELECT ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS id,
       e.abastesimientoSuper, e.gastoCombSuper, e.abastesimientoEXTRA,
       e.gastoCombEXTRA, e.abastesimientoDiesel, e.gastoCombDiesel,
       e.abastecimientoEco, e.gastoCombEco, e.abastecimientoElectricidad,
       e.gastoElectricidad, e.abastecimientoGas, e.gastoGas, e.id_hogar
FROM vivienda.enemdu_vivienda_final e;

-- ------------------------------------------


INSERT INTO  proyectoSchemaDefinitivo.arriendo(
                    idarriendo,
                    valorArriendo,
                    incluyePagoAgua,
                    incluyePagoLuz,
                    parentezcoPropietarioVivienda,
                    Hogar_idHogar
                    )

SELECT ROW_NUMBER() OVER (ORDER BY v.valorArriendo) AS id,
       v.valorArriendo, v.incluyePagoAgua, v.incluyePagoLuz, v.parentezcoPropietariovivienda,v.id_hogar
FROM vivienda.enemdu_vivienda_final v;











